[package]
name = "future-compat-await"
version = "0.1.0"
authors = ["David McGillicuddy <david.mcgillicuddy@moixa.com>"]
edition = "2018"

[dependencies]
futures = {version="0.3", features=["compat"]}
futures_01 = {version="0.1", package="futures"}
